/* Calibration is opt-in and specific to an experimental condition. */
const motorParameterKeys=['kd','exchange','motorRate','sites','hill','threshold'];
const motorSnapshot=p=>Object.fromEntries(motorParameterKeys.map(k=>[k,p[k]]));
const calibrationHistory=[];
function calibrationMatches(p){return !!p.calibration&&motorParameterKeys.every(k=>Math.abs(p[k]-p.calibration.parameters[k])<1e-10);}
const calFields=[['Name','条件名','Condition name'],['Strain','菌株・遺伝子型','Strain / genotype'],['Temperature','温度（不明ならunknown）','Temperature (or unknown)'],['Load','負荷・ビーズ径','Load / bead size'],['Assay','測定法・時間分解能','Assay / time resolution'],['Adaptation','適応状態・観測区間','Adaptation state / observation window'],['YBasis','CheY-Pの実測・推定・仮定の区別','CheY-P: measured, inferred or assumed'],['Source','出典・データID','Source / dataset ID']];
document.querySelector('.results-panel').insertAdjacentHTML('beforeend',`
<section class="research-card" id="calibrationCard">
<h2 data-ja="実験条件別のモーター校正・検証" data-en="Motor calibration & validation by experimental condition"></h2>
<p data-ja="初期値は探索用で、特定論文への自動適合は行いません。同じ菌株・温度・負荷・測定法・適応状態のデータを1条件として入力してください。異なる条件は別々に適合し、履歴で比較できます。" data-en="Defaults are exploratory; no paper is fitted automatically. Enter one condition with matching strain, temperature, load, assay and adaptation state. Fit different conditions separately and compare them in session history."></p>
<div class="calibration-inputs">${calFields.map(([id,ja,en])=>`<label><span data-ja="${ja}" data-en="${en}"></span><input id="cal${id}" type="text" maxlength="500" value=""></label>`).join('')}</div>
<label for="calData" data-ja="濃度ごとの観測値（カンマ・タブ区切り）" data-en="Observations by concentration (comma or tab separated)"></label>
<textarea id="calData" rows="7" maxlength="20000" spellcheck="false" placeholder="Y_uM,CW_bias,CW_dwell_s,CCW_dwell_s,role"></textarea>
<p class="helper" data-ja="列：Y_uM,CW_bias,CW_dwell_s,CCW_dwell_s,role。roleはfit（適合）またはvalidate（適合から除外）。biasのみ、または両方の平均滞在時間を入力可能。未測定値は空欄。実測の平均滞在時間を使い、中央値や打切り区間を除いた平均と混同しないでください。最大50点。" data-en="Columns: Y_uM,CW_bias,CW_dwell_s,CCW_dwell_s,role. Use fit or validate (excluded from fitting). Supply bias alone, or both mean dwells; leave unmeasured values blank. Use mean dwell estimates, not medians or means biased by excluding censored intervals. Maximum 50 rows."></p>
<div class="research-toolbar"><label><span data-ja="bias整合許容差" data-en="Bias consistency tolerance"></span><input id="calTolerance" type="number" min="0" max="0.1" step="0.001" value="0.005"></label><button id="calFit" data-ja="適合して適用" data-en="Fit & apply"></button><button id="calReset" data-ja="入力をクリア" data-en="Clear inputs"></button><button id="calSynthetic" data-ja="人工データ例" data-en="Synthetic example"></button><button id="calExample" data-ja="文献例を読み込む" data-en="Load literature example"></button><button id="calCsv" disabled data-ja="校正結果CSV" data-en="Calibration CSV"></button></div>
<p class="helper" data-ja="固定：K_D・結合交換速度・部位数・急峻さ。適合：占有率しきい値、滞在時間がある場合のみ切替速度。滞在時間比がbiasを規定するため、同じ行のbiasは独立な3つ目の適合制約として数えません。濃度の不確かさ・温度依存・負荷依存・FliM再構成は推定しません。" data-en="Fixed: K_D, binding exchange, site count and steepness. Fitted: occupancy threshold; switching scale only when dwells are available. Dwell ratios determine bias, so bias on the same row is a consistency check, not a third independent fit constraint. Concentration uncertainty, temperature/load laws and FliM remodeling are not inferred."></p>
<p id="calMessage" role="status" aria-live="polite"></p><div id="calReport"></div>
<div class="research-toolbar"><label><span data-ja="条件別履歴（このセッションのみ）" data-en="Condition history (this session)"></span><select id="calHistory"></select></label><button id="calRestore" data-ja="選択した適合を適用" data-en="Apply selected fit"></button></div>
<div class="research-toolbar"><label><input type="checkbox" id="clampMode"><span data-ja="モーター入力を一定CheY-Pにする" data-en="Use constant CheY-P motor input"></span></label><label>CheY-P (µM)<input id="clampY" type="number" min="0" max="30" step="0.01" value="3.15"></label></div><p id="clampStatus" class="helper"></p>
<details><summary data-ja="文献ごとの検証対象と限界" data-en="What each reference constrains"></summary>
<ul><li><a href="https://doi.org/10.1126/science.287.5458.1652">Cluzel et al. 2000</a>: CheY-P–CW concentration response. This constrains response shape, not an independent binding K_D or dwell kinetics.</li><li><a href="https://doi.org/10.1016/j.jmb.2009.05.039">Yuan, Fahrner &amp; Berg 2009</a>: switching under different motor loads; fit each load separately.</li><li><a href="https://doi.org/10.1016/j.jmb.2013.02.016">Yuan &amp; Berg 2013</a>: motor adaptation and ultrasensitivity; adapted and immediate responses are distinct conditions.</li><li><a href="https://doi.org/10.7554/eLife.01916">Mears et al. 2014</a>: optional population-summary example. CheY-P is model-inferred; dwells are inverse-rate conversions, not digitized dwell distributions.</li></ul>
<p data-ja="これらの文献を統合して普遍的パラメーターを得たものではありません。数値例以外の論文データは組み込んでいません。ユーザー入力は出典を記録して適合し、未知の条件を既知とみなしません。" data-en="These references do not define a pooled universal parameter set. Only the optional summary example is preloaded numerically. User data retain their provenance; unknown conditions remain unknown."></p></details></section>`);
document.querySelector('.results-panel').insertAdjacentHTML('afterbegin','<p id="inputModeNotice" class="helper" role="status"></p>');
function calibrationCondition(){const c={};for(const [id] of calFields){c[id]=el('cal'+id).value.trim();if(!c[id])throw Error(tx('実験条件をすべて記入してください。不明はunknownとしてください。','Complete all condition fields; enter unknown where unavailable.'));}return c;}
function fitCalibration(){if(el('calTolerance').value.trim()==='')throw Error('Enter a bias consistency tolerance.');const conditions=calibrationCondition(),rows=MotorFit.parse(el('calData').value),tolerance=Number(el('calTolerance').value),fit=MotorFit.fit(E,state,rows,tolerance);const record={conditions,targets:rows,parameters:motorSnapshot(fit.params),scope:'condition_specific_stationary_summary_fit',fitted:fit.fitted,fixed:fit.fixed,biasTolerance:tolerance,objective:fit.objective,method:fit.method,loss:fit.loss,atBoundary:fit.atBoundary,model:'0.6'};state={...fit.params,calibration:record};calibrationHistory.push(record);el('calHistory').innerHTML=calibrationHistory.map((r,i)=>`<option value="${i}">${i+1}: ${esc(r.conditions.Name)}</option>`).join('');el('calHistory').value=calibrationHistory.length-1;clearPreset();runAndRender();el('calMessage').textContent=tx('適合を適用しました。残差と未使用検証点を確認してください。適合は実験的妥当性の保証ではありません。','Fit applied. Inspect residuals and held-out points; a numerical fit does not establish experimental validity.');}
let calibrationRenderKey='';
function renderCalibration(){const key=JSON.stringify([language,motorSnapshot(state),state.calibration,state.inputMode,state.clampY]);if(key===calibrationRenderKey)return;calibrationRenderKey=key;const c=E.config(state);el('derivedRates').textContent=`k_on = ${c.kon.toFixed(4)} µM⁻¹ s⁻¹; k_off = ${c.koff.toFixed(4)} s⁻¹; 1/k_off = ${(1/c.koff).toFixed(4)} s`;const record=state.calibration;el('calCsv').disabled=!record;if(!record)el('calReport').textContent=tx('未校正：探索用初期値。データを入力して適合できます。','Uncalibrated exploratory parameters. Enter data to fit.');else{const fmt=v=>v===null?'—':Number.isFinite(v)?v.toFixed(5):'∞',rows=MotorFit.evaluate(E,state,record.targets);el('calReport').innerHTML=`<p class="calibration-state">${calibrationMatches(state)?tx('条件限定の適合','Condition-specific fit'):tx('パラメーター変更済み：保存済み目標との比較','Parameters changed: comparison with saved targets')}</p><p>${esc(record.conditions.Name)} — ${esc(record.conditions.Source)}</p><p>${esc(Object.entries(record.conditions).map(([k,v])=>k+': '+v).join(' | '))}</p><div class="table-scroll"><table><tr><th>${tx('用途 / Y (µM)','Role / Y (µM)')}</th><th>${tx('指標','Metric')}</th><th>${tx('目標','Target')}</th><th>${tx('現モデル','Current model')}</th><th>${tx('残差','Residual')}</th></tr>${rows.flatMap(r=>[['CW bias','cw'],['CW dwell (s)','cwDwell'],['CCW dwell (s)','ccwDwell']].map(([name,k])=>`<tr><td>${r.role} / ${r.Y}</td><td>${name}</td><td>${fmt(r[k])}</td><td>${fmt(r.prediction[k])}</td><td>${fmt(r[k]===null?null:r.prediction[k]-r[k])}</td></tr>`)).join('')}</table></div><p>q_half=${state.threshold.toFixed(6)}; w=${state.motorRate.toFixed(6)} s⁻¹; ${tx('適合時の目的関数','Objective at fit')}=${record.loss.toPrecision(4)}</p><p>${record.atBoundary?tx('探索範囲の境界に到達：適合を要確認。','Parameter boundary reached: inspect the fit.'):''} ${record.targets.some(r=>r.role==='validate')?tx('validate行は適合に使用していません。独立検証かどうかはデータの由来によります。','Validate rows were excluded from fitting; independence depends on data provenance.'):tx('未使用の検証点はありません。','No held-out validation points.')}</p><p class="helper">${esc(record.objective)}</p>`;}
el('clampMode').checked=state.inputMode==='clamp';el('clampY').value=state.clampY;el('clampStatus').textContent=state.inputMode==='clamp'?tx('一定入力モード。上流経路の濃度と応答指標は別に計算します。','Constant motor input. Upstream pools and response metrics are computed separately.'):tx('経路モード。校正は記録された実験条件・濃度の範囲に限定されます。','Pathway mode. Fit scope is limited to the recorded experimental conditions and concentrations.');el('inputModeNotice').textContent=state.inputMode==='clamp'?tx(`モーター入力固定：${state.clampY} µM。`,`Constant motor input: ${state.clampY} µM.`):tx('経路モード：曲線はモーターの集団平均、CGは5モーターの1試行。CG速度は模式表現です。','Pathway mode: curve = motor ensemble mean; CG = one realization of five motors. CG speed is illustrative.');document.querySelector('.node.motor b').textContent=tx('集団平均CW確率','Ensemble CW probability');}
const calibrationRun=runAndRender;runAndRender=function(){calibrationRun();renderCalibration();};const calibrationTranslate=translate;translate=function(){calibrationTranslate();renderCalibration();};
const calGuard=fn=>()=>{try{fn();}catch(e){el('calMessage').textContent=tx('適合できません：','Cannot fit: ')+e.message;}};
el('calFit').onclick=calGuard(fitCalibration);
el('calReset').onclick=()=>{for(const [id] of calFields)el('cal'+id).value='';el('calData').value='';el('calMessage').textContent=tx('入力をクリアしました。適用中のパラメーターは保持しています。','Inputs cleared; applied parameters are retained.');};
function loadCalibrationExample(synthetic){const conditions=synthetic?{Name:'Synthetic demonstration (not experimental)',Strain:'Simulated',Temperature:'Not modeled',Load:'Not modeled',Assay:'Exact stationary model summaries',Adaptation:'Fixed motor site count',YBasis:'Known simulated input',Source:'ChemoSim synthetic generator; not independent validation'}:{Name:'Mears 2014 / conditional summary example',Strain:'E. coli HCB1660; FliC S219C',Temperature:'unknown (not encoded)',Load:'Optical trap / swimming flagella',Assay:'Fluorescent waveform classification; 100 ms windows',Adaptation:'Chemotaxis WT population summaries',YBasis:'Model-inferred mean 2.59 µM approximated as constant',Source:'10.7554/eLife.01916 Table 3; dwells = inverse reported rates'};for(const [id] of calFields)el('cal'+id).value=conditions[id];const rows=synthetic?[1.8,2.5,3.15,4,5].map((Y,i)=>{const s=E.stationary(Y,{...state,threshold:.47,motorRate:3});return [Y,s.cw,s.cwDwell,s.ccwDwell,i===3?'validate':'fit'];}):[[2.59,.13,1/1.7,1/.26,'fit']];el('calData').value='Y_uM,CW_bias,CW_dwell_s,CCW_dwell_s,role\n'+rows.map(r=>r.join(',')).join('\n');el('calTolerance').value=.005;el('calMessage').textContent=tx('例を読み込みました。まだ適用していません。','Example loaded; parameters have not been changed.');}
el('calSynthetic').onclick=()=>loadCalibrationExample(true);el('calExample').onclick=()=>loadCalibrationExample(false);
el('calRestore').onclick=()=>{const record=calibrationHistory[Number(el('calHistory').value)];if(!record)return;for(const [id] of calFields)el('cal'+id).value=record.conditions[id];el('calData').value='Y_uM,CW_bias,CW_dwell_s,CCW_dwell_s,role\n'+record.targets.map(r=>[r.Y,r.cw??'',r.cwDwell??'',r.ccwDwell??'',r.role].join(',')).join('\n');el('calTolerance').value=record.biasTolerance;applyState({...state,...record.parameters,calibration:record},null);};
for(const id of [...calFields.map(([id])=>'cal'+id),'calData','calTolerance'])el(id).oninput=()=>{el('calMessage').textContent=tx('入力変更：再適合するまで表は保存済みの目標を示します。','Inputs edited: the table retains saved targets until you refit.');};
el('clampMode').onchange=()=>{state.inputMode=el('clampMode').checked?'clamp':'pathway';runAndRender();};el('clampY').onchange=()=>{const y=Number(el('clampY').value);if(el('clampY').value.trim()===''||!Number.isFinite(y)||y<0||y>30){el('clampY').value=state.clampY;return;}state.clampY=y;runAndRender();};
el('calCsv').onclick=()=>{if(!state.calibration)return;const r=state.calibration;csv([['metadata','role','Y_uM','metric','target','prediction','residual'],...MotorFit.evaluate(E,state,r.targets).flatMap(t=>['cw','cwDwell','ccwDwell'].map(k=>[JSON.stringify({record:r,current_parameters:motorSnapshot(state),parameter_snapshot_matches:calibrationMatches(state)}),t.role,t.Y,k,t[k],t.prediction[k],t[k]===null?'':t.prediction[k]-t[k]]))],'chemosim-motor-calibration.csv');};
renderCalibration();translate();
