/* Source-independent fitting of conditional stationary summary observations. */
const MotorFit=(()=>{
function parse(text){const lines=text.trim().split(/\r?\n/).filter(s=>s.trim()&&!s.trim().startsWith('#'));if(!lines.length||lines.length>51)throw Error('Enter 1–50 data rows.');const rows=[];for(let i=0;i<lines.length;i++){const v=lines[i].trim().split(/[\t,]/).map(s=>s.trim());if(i===0&&v[0]==='Y_uM')continue;if(v.length!==5)throw Error(`Row ${i+1}: use five comma/tab-separated fields: Y_uM,CW_bias,CW_dwell_s,CCW_dwell_s,role.`);const num=s=>s===''?null:Number(s),[Y,cw,cwDwell,ccwDwell]=v.slice(0,4).map(num),role=v[4];if(Y===null||!Number.isFinite(Y)||Y<=0||Y>30||!['fit','validate'].includes(role))throw Error(`Row ${i+1}: Y must be in (0,30], role fit or validate.`);if(cw!==null&&(!Number.isFinite(cw)||cw<=0||cw>=1))throw Error(`Row ${i+1}: bias must be in (0,1).`);if((cwDwell===null)!==(ccwDwell===null)||[cwDwell,ccwDwell].some(x=>x!==null&&(!Number.isFinite(x)||x<=0)))throw Error(`Row ${i+1}: supply both positive mean dwells, or leave both blank.`);if(cw===null&&cwDwell===null)throw Error(`Row ${i+1}: no observations.`);rows.push({Y,cw,cwDwell,ccwDwell,role});}if(!rows.length||rows.length>50)throw Error('Enter 1–50 data rows.');return rows;}
function check(rows,tolerance){if(!Number.isFinite(tolerance)||tolerance<0||tolerance>.1)throw Error('Bias consistency tolerance must be 0–0.1.');for(const r of rows)if(r.cw!==null&&r.cwDwell!==null&&Math.abs(r.cw-r.cwDwell/(r.cwDwell+r.ccwDwell))>tolerance)throw Error('CW bias and paired mean dwells are inconsistent with stationary alternating states. Check pooling, censoring and rounding; do not combine incompatible observations.');}
function minimize(fn,lo,hi,n=32){const phi=(Math.sqrt(5)-1)/2;let a=hi-phi*(hi-lo),b=lo+phi*(hi-lo),fa=fn(a),fb=fn(b);for(let i=0;i<n;i++){if(fa<fb){hi=b;b=a;fb=fa;a=hi-phi*(hi-lo);fa=fn(a);}else{lo=a;a=b;fa=fb;b=lo+phi*(hi-lo);fb=fn(b);}}return fa<fb?{x:a,loss:fa}:{x:b,loss:fb};}
function evaluate(engine,p,rows){return rows.map(r=>({...r,prediction:engine.stationary(r.Y,p)}));}
function fit(engine,p,rows,tolerance=.005){check(rows,tolerance);const train=rows.filter(r=>r.role==='fit');if(!train.length)throw Error('At least one fit row is required.');const hasDwells=train.some(r=>r.cwDwell!==null);function objective(q,w){let total=0,n=0;for(const r of train){const s=engine.stationary(r.Y,{...p,threshold:q,motorRate:w});if(r.cwDwell!==null){total+=Math.log(s.cwDwell/r.cwDwell)**2+Math.log(s.ccwDwell/r.ccwDwell)**2;n+=2;}else{total+=((s.cw-r.cw)/.05)**2;n++;}}return Number.isFinite(total)?total/n:1e100;}
function bestW(q){if(!hasDwells)return {x:Math.log(p.motorRate),loss:objective(q,p.motorRate)};return minimize(z=>objective(q,Math.exp(z)),Math.log(.01),Math.log(100),28);}
// Coarse scan before local refinement reduces sensitivity to the starting parameters.
const candidates=Array.from({length:25},(_,i)=>{const q=.01+.98*i/24;return {q,...bestW(q)};}).sort((a,b)=>a.loss-b.loss);const best=candidates[0],step=.98/24;const qfit=minimize(q=>bestW(q).loss,Math.max(.01,best.q-step),Math.min(.99,best.q+step),30),wfit=bestW(qfit.x);const params={...p,threshold:qfit.x,motorRate:Math.exp(wfit.x)};if(!Number.isFinite(wfit.loss)||wfit.loss>=1e90)throw Error('No finite fit in the supported parameter range.');
return {params,loss:wfit.loss,hasDwells,fitted:hasDwells?['threshold','motorRate']:['threshold'],fixed:hasDwells?['kd','exchange','sites','hill']:['kd','exchange','sites','hill','motorRate'],atBoundary:params.threshold<.0101||params.threshold>.9899||(hasDwells&&(params.motorRate<.0101||params.motorRate>99.9)),rows:evaluate(engine,params,rows),method:'Bounded coarse scan + nested golden search; numerical fit, no confidence intervals',objective:'Rows with paired dwells: squared log-ratio residuals (bias used only for consistency). Bias-only rows: squared residual / 0.05². Equal weight per independent summary; scales are conventions, not measured standard errors.'};}
return {parse,check,fit,evaluate};
})();
if(typeof module!=='undefined')module.exports=MotorFit;
