/* Research workspace: reproducible batches, parameter grids and portable exports. */
let language='en',batch=null,grid=null,revision=0,job=0;
const E=ResearchEngine,tx=(ja,en)=>language==='ja'?ja:en;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const knobs=[['kd','K_D (µM)',.1,30,.05,3.15],['exchange','Binding exchange at Y_ref (s⁻¹)',.1,50,.1,6.3],['motorRate','Motor switching scale (s⁻¹)',.01,100,.01,2],['sites','結合部位数 / Binding sites',4,100,1,34],['hill','切替応答の急峻さ / Switching steepness',1,30,.5,9.5],['threshold','半応答占有率 / Half-response occupancy',.01,.99,.001,.5]];
Object.assign(defaults,{kd:3.15,exchange:6.3,motorRate:2,sites:34,hill:9.5,threshold:.5,inputMode:'pathway',clampY:3.15});Object.assign(state,defaults);
document.querySelector('.brand em').textContent='MODEL 0.6';
document.querySelector('.motor-parameter-section').innerHTML=`<h2 data-ja="結合とモーター" data-en="Binding & motor"></h2><p class="helper" data-ja="K_D：親和性。結合交換速度：基準CheY-P 3.15 µMでの占有率緩和速度。回転切替速度は独立です。結合は独立部位モデルです。" data-en="K_D sets affinity. Exchange sets occupancy relaxation at reference CheY-P = 3.15 µM. Motor switching has a separate scale. Binding sites are independent."></p>${knobs.map(([id,label,min,max,step,value])=>`<label class="research-label">${label}<input id="r_${id}" type="number" min="${min}" max="${max}" step="${step}" value="${value}"></label>`).join('')}<p id="derivedRates" class="helper"></p><div hidden><input id="motorInstability"><output id="motorInstabilityOut"></output></div>`;
document.querySelector('.top-actions').insertAdjacentHTML('afterbegin','<button id="langBtn" class="ghost-btn">Japanese</button><button id="figureBtn" class="ghost-btn">Figure mode</button>');
document.querySelector('.results-panel').insertAdjacentHTML('beforeend',`
<section class="research-card"><h2 data-ja="反復計算・滞在時間分布" data-en="Replicates & dwell-time distributions"></h2>
<div class="research-toolbar"><label data-ja="反復数" data-en="Replicates"></label><select id="replicates"><option>100</option><option>300</option><option>1000</option></select><label>Seed<input id="seed" type="number" min="0" max="4294967295" value="3107"></label><label data-ja="解析開始 (s)" data-en="Analysis start (s)"></label><input id="windowStart" type="number" min="0" max="59" value="0"><button id="batchBtn" data-ja="反復計算" data-en="Run batch"></button><button id="cancelBtn" data-ja="中止" data-en="Cancel"></button><button id="batchCsv" disabled>CSV</button></div>
<p id="researchStatus" role="status" aria-live="polite"></p><div id="statistics"></div><div id="dwellPlot" class="svg-plot"></div>
<p class="helper" data-ja="各反復は5モーター・60秒。95% CIは独立反復の平均に対する正規近似。ヒストグラムは両端打切りを除く完全区間のみ（短い区間に偏る可能性あり）。CSVには打切り区間も含みます。" data-en="Each replicate: 5 motors, 60 s. 95% CI: normal approximation across independent replicates. Histograms use complete dwells only, excluding left/right censoring (potential short-dwell bias). CSV includes censored intervals."></p></section>
<section class="research-card"><h2 data-ja="2パラメーター探索" data-en="Two-parameter sweep"></h2><div class="research-toolbar"><label>X <select id="axisX"></select></label><label>Y <select id="axisY"></select></label><label data-ja="出力" data-en="Output"></label><select id="gridMetric"><option value="cw">CW fraction</option><option value="tumble">Tumble fraction</option><option value="frequency">Switches / motor / s</option><option value="bundle">Full-bundle fraction</option></select><label>Grid<select id="gridSize"><option>5</option><option>9</option></select></label><label data-ja="各点の反復数" data-en="Replicates / point"></label><select id="gridReps"><option>10</option><option>30</option></select><button id="gridBtn" data-ja="探索する" data-en="Run sweep"></button><button id="gridCsv" disabled>CSV</button></div><p class="helper" data-ja="範囲：タンパク質量0.25–4倍、K_D 0.5–12.6、交換速度0.5–20、切替速度0.1–10、部位数10–70、急峻さ2–30、半応答占有率0.2–0.8。全軸は線形。セルを選ぶと条件とSDを表示します。" data-en="Linear ranges: proteins 0.25–4×; K_D 0.5–12.6; exchange 0.5–20; switching scale 0.1–10; sites 10–70; steepness 2–30; half occupancy 0.2–0.8. Select a cell to inspect its condition and SD."></p><div id="heatmap" class="svg-plot"></div><p id="gridDetail"></p></section>
<section class="research-card"><h2 data-ja="データ・画像出力" data-en="Data & image export"></h2><div class="research-toolbar"><button id="traceCsv" data-ja="時系列CSV" data-en="Time-course CSV"></button><select id="exportTarget"><option value="signal">Signal</option><option value="cell">CG</option><option value="dwell">Dwell distribution</option><option value="heat">Heatmap</option><option value="figure">Figure A–D</option></select><button id="svgBtn">SVG</button><button id="pngBtn">PNG (2400 px)</button></div><p class="helper" data-ja="グラフはベクターSVG、CGは現在フレームのPNGを埋め込んだSVGです。Figure modeはA:CG、B:時系列、C:滞在時間、D:探索を白背景で配置します。" data-en="Charts are vector SVG; CG SVG embeds the current PNG frame. Figure mode arranges A: CG, B: signals, C: dwell times, D: sweep on white panels."></p><div id="figurePreview" hidden></div></section>
<section class="research-card"><details open><summary data-ja="モデル式・パラメーター根拠・制約" data-en="Model equations, parameter provenance & limitations"></summary><div id="modelDocs"></div></details></section>`);
const axes=[...proteinDefs.map(p=>[p.id,p.name,.25,4]),['kd','K_D',.5,12.6],['exchange','Binding exchange',.5,20],['motorRate','Motor switching scale',.1,10],['sites','Binding sites',10,70],['hill','Switching steepness',2,30],['threshold','Half occupancy',.2,.8]];
for(const id of ['axisX','axisY'])el(id).innerHTML=axes.map(a=>`<option value="${a[0]}">${a[1]}</option>`).join('');el('axisX').value='kd';el('axisY').value='exchange';
for(const [id,,min,max] of knobs)el('r_'+id).onchange=()=>{const n=Number(el('r_'+id).value);state[id]=Math.max(min,Math.min(max,Number.isFinite(n)?n:defaults[id]));el('r_'+id).value=state[id];clearPreset();runAndRender();};
const originalRun=runAndRender;
runAndRender=function(){revision++;job++;batch=null;grid=null;el('batchCsv').disabled=true;el('gridCsv').disabled=true;el('statistics').innerHTML='';el('dwellPlot').innerHTML='';el('heatmap').innerHTML='';el('gridDetail').textContent='';el('figurePreview').hidden=true;el('researchStatus').textContent=tx('条件変更後は再計算してください。','Recompute analyses after changing conditions.');for(const [id] of knobs)el('r_'+id).value=state[id]??defaults[id];originalRun();el('motorKoffReadout').textContent=`${E.config(state).koff.toFixed(3)} s⁻¹`;el('motorLifetimeReadout').textContent=`${(1/E.config(state).koff).toFixed(3)} s`;translate();};
const oldScene=renderCellScene;
renderCellScene=function(r,i,phase){oldScene(r,i,phase);renderMotors(lastMotorTrace[Math.floor(i)]);el('biasFill').style.width=`${r.cw[Math.floor(i)]*100}%`;translate();};
function validSettings(){const seed=Number(el('seed').value),start=Number(el('windowStart').value);if(!Number.isInteger(seed)||seed<0||seed>4294967295||!Number.isFinite(start)||start<0||start>=60)throw Error(tx('Seedまたは解析開始時刻が不正です。','Invalid seed or analysis start.'));return {seed,start};}
const tick=()=>new Promise(resolve=>setTimeout(resolve,0));
async function runBatch(){const {seed,start}=validSettings(),token=++job,params={...state},r=simulate(params),n=Number(el('replicates').value),runs=[];batch=null;el('batchCsv').disabled=true;for(let i=0;i<n;i++){const s=(seed+i*7919)>>>0;const tr=E.trace(r,params,s);runs.push({seed:s,...E.stats(tr,start)});if(i%5===0){el('researchStatus').textContent=`${i+1}/${n}`;await tick();if(token!==job)return;}}batch={params,seed,start,runs};el('batchCsv').disabled=false;showBatch();el('researchStatus').textContent=tx('反復計算完了','Batch complete');}
function showBatch(){if(!batch)return;el('statistics').innerHTML=`<table><thead><tr><th>Metric</th><th>Mean</th><th>SD</th><th>95% CI</th></tr></thead><tbody>${['cw','tumble','bundle','frequency'].map(k=>{const s=E.summary(batch.runs.map(r=>r[k]));return `<tr><td>${k==='frequency'?'Switches / motor / s':k+' fraction'}</td><td>${s.mean.toFixed(4)}</td><td>${s.sd.toFixed(4)}</td><td>${s.low.toFixed(4)} – ${s.high.toFixed(4)}</td></tr>`;}).join('')}</tbody></table>`;el('dwellPlot').innerHTML=dwellSVG();}
async function runGrid(){const {seed,start}=validSettings(),x=axes.find(a=>a[0]===el('axisX').value),y=axes.find(a=>a[0]===el('axisY').value);if(x[0]===y[0])throw Error(tx('異なる軸を選んでください。','Choose different axes.'));const token=++job,base={...state},size=Number(el('gridSize').value),n=Number(el('gridReps').value),metric=el('gridMetric').value,cells=[];grid=null;el('gridCsv').disabled=true;for(let j=0;j<size;j++)for(let i=0;i<size;i++){const xv=x[2]+(x[3]-x[2])*i/(size-1),yv=y[2]+(y[3]-y[2])*j/(size-1),p={...base,[x[0]]:xv,[y[0]]:yv};p.sites=Math.round(p.sites);const r=simulate(p),values=[];for(let k=0;k<n;k++)values.push(E.stats(E.trace(r,p,(seed+(j*size+i)*104729+k*7919)>>>0),start)[metric]);cells.push({i,j,x:p[x[0]],y:p[y[0]],...E.summary(values)});el('researchStatus').textContent=`${cells.length}/${size*size}`;await tick();if(token!==job)return;}grid={base,seed,start,x,y,size,n,metric,cells};el('gridCsv').disabled=false;el('heatmap').innerHTML=heatSVG();el('heatmap').querySelectorAll('[data-cell]').forEach(node=>node.onclick=()=>{const c=grid.cells[Number(node.dataset.cell)];el('gridDetail').textContent=`${x[1]}=${c.x.toFixed(3)}, ${y[1]}=${c.y.toFixed(3)}: ${metric}=${c.mean.toFixed(4)} ± ${c.sd.toFixed(4)} SD; n=${n}`;});el('researchStatus').textContent=tx('探索完了','Sweep complete');}
function guarded(fn){return async()=>{try{await fn();}catch(e){el('researchStatus').textContent=e.message;}};}
el('batchBtn').onclick=guarded(runBatch);el('gridBtn').onclick=guarded(runGrid);el('cancelBtn').onclick=()=>{job++;el('researchStatus').textContent=tx('計算を中止しました。','Calculation cancelled.');};
for(const id of ['seed','windowStart','replicates'])el(id).onchange=()=>{job++;batch=null;grid=null;el('batchCsv').disabled=el('gridCsv').disabled=true;el('statistics').innerHTML=el('dwellPlot').innerHTML=el('heatmap').innerHTML='';};
function download(data,name,type){const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csv(rows,name){download('\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n'),name,'text/csv;charset=utf-8');}
function metadata(p,seed,start=0){return JSON.stringify({model:'0.6',params:p,upstream:Upstream.provenance(p),seed,analysis_start_s:start,analysis_end_s:60,signal_bin_s:.2,input_mode:p.inputMode??'pathway',method:'joint_binding_motor_Gillespie_piecewise_signal',derived_rates:E.config(p),calibration:p.calibration??null,calibration_current:typeof calibrationMatches==='function'?calibrationMatches(p):false,initialization:'joint_stationary',mean_method:'binomial_occupancy_and_motor_probability_ODE_RK4'});}
el('traceCsv').onclick=()=>{const meta=metadata(state,lastMotorTrace.seed);csv([['metadata','time_s','CheY_P_uM','activity','CheA_long_P_uM','ensemble_CW','mean_occupancy','stimulus_uM',...Array.from({length:5},(_,i)=>`M${i+1}_CW`),...Array.from({length:5},(_,i)=>`M${i+1}_bound`)],...lastResult.time.map((t,i)=>[meta,t,lastResult.cheYP[i],lastResult.activity[i],lastResult.cheAP[i],lastResult.cw[i],lastResult.occupancy[i],lastResult.stimulus[i],...lastMotorTrace[i].map(Number),...lastMotorTrace.occupancy[i]])],'chemosim-timecourse.csv');};
el('batchCsv').onclick=()=>{if(!batch)return;const rows=[['metadata','replicate','seed','CW_fraction','tumble_fraction','full_bundle_fraction','switches_per_motor_s','motor','state','duration_s','left_censored','right_censored']];batch.runs.forEach((r,i)=>r.dwells.forEach(d=>rows.push([metadata(batch.params,batch.seed,batch.start),i+1,r.seed,r.cw,r.tumble,r.bundle,r.frequency,d.motor+1,d.state,d.duration,d.left_censored,d.right_censored])));csv(rows,'chemosim-replicates-dwells.csv');};
el('gridCsv').onclick=()=>{if(!grid)return;csv([['metadata','x_parameter','y_parameter','x','y','metric','n','mean','sd','ci95_low','ci95_high'],...grid.cells.map(c=>[metadata(grid.base,grid.seed,grid.start),grid.x[0],grid.y[0],c.x,c.y,grid.metric,c.n,c.mean,c.sd,c.low,c.high])],'chemosim-sweep.csv');};
const svgWrap=(body,w=720,h=360)=>`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><rect width="100%" height="100%" fill="white"/><g font-family="Arial, sans-serif" font-size="14" fill="#172b35">${body}</g></svg>`;
const textSVG=(x,y,s,extra='')=>`<text x="${x}" y="${y}" ${extra}>${esc(s)}</text>`;
function signalSVG(){const r=lastResult,max=Math.max(1,...r.cheYP)*1.1,path=(v,max)=>v.map((y,i)=>`${i?'L':'M'}${60+r.time[i]*10},${300-y/max*245}`).join(' ');return svgWrap(textSVG(60,24,'CheY-P (µM) / ensemble CW probability')+`<path d="M60 45V300H660" stroke="#172b35" fill="none"/>`+Array.from({length:7},(_,i)=>textSVG(60+i*100,322,i*10)).join('')+Array.from({length:5},(_,i)=>textSVG(5,300-i*61,(max*i/4).toFixed(1))+textSVG(669,300-i*61,(i/4).toFixed(2))).join('')+`<path d="${path(r.cheYP,max)}" stroke="#007f77" stroke-width="2" fill="none"/><path d="${path(r.cw,1)}" stroke="#ba4a00" stroke-width="2" fill="none"/>`+textSVG(320,348,'Time (s)')+textSVG(400,42,'Teal: Y-P / orange: CW'));}
function dwellSVG(){if(!batch)return svgWrap(textSVG(50,100,tx('反復計算が必要です','Run a batch first')));const d=batch.runs.flatMap(r=>r.dwells).filter(d=>!d.left_censored&&!d.right_censored),max=d.reduce((max,d)=>Math.max(max,d.duration),1),bins=20;let body=textSVG(55,25,'Complete CW / CCW dwell counts (censored excluded)');const counts=['CW','CCW'].map(s=>Array.from({length:bins},(_,i)=>d.filter(d=>d.state===s&&Math.min(bins-1,Math.floor(d.duration/max*bins))===i).length)),top=Math.max(1,...counts.flat());for(let j=0;j<2;j++)for(let i=0;i<bins;i++)body+=`<rect x="${60+i*29+j*13}" y="${300-counts[j][i]/top*240}" width="12" height="${counts[j][i]/top*240}" fill="${j?'#007f77':'#ba4a00'}"/>`;body+=textSVG(60,324,'0')+textSVG(610,324,max.toFixed(2)+' s')+textSVG(60,50,'max count: '+top)+textSVG(250,348,'Orange: CW; teal: CCW; n='+d.length);return svgWrap(body);}
function heatSVG(){if(!grid)return svgWrap(textSVG(50,100,tx('探索計算が必要です','Run a sweep first')));const {size,cells,x,y,metric}=grid,lo=Math.min(...cells.map(c=>c.mean)),hi=Math.max(...cells.map(c=>c.mean)),cw=520/size,ch=230/size;let body=textSVG(60,25,metric+` [${lo.toFixed(3)} – ${hi.toFixed(3)}]`);cells.forEach((c,k)=>{const f=(c.mean-lo)/(hi-lo||1),color=`rgb(${Math.round(240-220*f)},${Math.round(247-125*f)},${Math.round(250-120*f)})`;body+=`<rect data-cell="${k}" x="${95+c.i*cw}" y="${55+(size-1-c.j)*ch}" width="${cw}" height="${ch}" fill="${color}" stroke="white"><title>${esc(`${x[1]}=${c.x}, ${y[1]}=${c.y}; mean=${c.mean}, SD=${c.sd}`)}</title></rect>`;});for(let i=0;i<size;i++){body+=textSVG(95+(i+.5)*cw,308,(x[2]+(x[3]-x[2])*i/(size-1)).toFixed(2),'text-anchor="middle"')+textSVG(85,55+(size-i-.5)*ch,(y[2]+(y[3]-y[2])*i/(size-1)).toFixed(2),'text-anchor="end"');}body+=textSVG(330,346,x[1])+textSVG(20,180,y[1],'transform="rotate(-90 20 180)"');return svgWrap(body);}
function cellSVG(){const c=el('cellScene');return svgWrap(`<image x="0" y="0" width="720" height="330" preserveAspectRatio="xMidYMid meet" href="${c.toDataURL('image/png')}"/>`+textSVG(20,352,`CG snapshot: t=${lastResult.time[Math.floor(playbackIndex)].toFixed(1)} s; raster embedded`));}
function figureSVG(){const panels=[cellSVG(),signalSVG(),dwellSVG(),heatSVG()];return svgWrap(panels.map((s,i)=>`<g transform="translate(${(i%2)*740+20} ${Math.floor(i/2)*390+45})">${textSVG(0,-8,'ABCD'[i],'font-weight="bold" font-size="22"')}${s}</g>`).join('')+textSVG(20,845,`ChemoSim 0.6 | Motor fit: ${typeof calibrationMatches==='function'&&calibrationMatches(state)?'condition-specific':'not current'} | upstream/binding assumptions | seed=${lastMotorTrace.seed} | batch n=${batch?.runs.length||0} | sweep n/point=${grid?.n||0}`)+textSVG(20,870,knobs.map(([id])=>`${id}=${state[id]}`).join('; ')),1500,900);}
function selectedSVG(){return ({signal:signalSVG,cell:cellSVG,dwell:dwellSVG,heat:heatSVG,figure:figureSVG})[el('exportTarget').value]();}
el('svgBtn').onclick=()=>download(selectedSVG(),`chemosim-${el('exportTarget').value}.svg`,'image/svg+xml');
el('pngBtn').onclick=guarded(async()=>{const svg=selectedSVG(),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('PNG export failed'));img.src=url;});const c=document.createElement('canvas');c.width=2400;c.height=Math.round(2400*img.height/img.width);c.getContext('2d').drawImage(img,0,0,c.width,c.height);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));if(!blob)throw Error('PNG export failed');download(blob,`chemosim-${el('exportTarget').value}-2400px.png`);}finally{URL.revokeObjectURL(url);}});
el('figureBtn').onclick=()=>{el('figurePreview').hidden=false;el('figurePreview').innerHTML=figureSVG();el('exportTarget').value='figure';el('figurePreview').scrollIntoView({behavior:'smooth'});};
function docs(){el('modelDocs').innerHTML=`<p>${tx('結合定数と上流経路は仮定値です。モーターの校正範囲と根拠は校正パネルに示します。単一条件での平均値の一致は、濃度応答全体や滞在時間分布の検証ではありません。','Binding parameters and uncalibrated upstream rates remain assumptions; receptor reference reconstructions are documented above. See the calibration panel for motor fit scope and provenance. Matching means at one condition does not validate the full concentration-response curve or dwell-time distributions.')}</p><pre>[X]total = molecule_count / (602.214076 × volume_fL) [µM]
A = A_long_total − AP; Y = Y_total − YP; B = B_total − BP
vA = kAuto·a·A; vY = kAY·AP·Y; vB = kAB·AP·B
vZ = kYoff·YP + kZ·Z_total·YP²/(KZ²+YP²)
dAP/dt = vA − vY − vB; dYP/dt = vY − vZ
dBP/dt = vB − kBoff·BP
dm/dt = kR·R_total·(1−a) − kB·(B+100BP)·a
m ∈ [0,4] (effective coordinate); freeze option: dm/dt=0
Reference: R(L)=β/[1+(L/K1)^h]+(1−β)/[1+(L/K2)^h]
a = logistic(logit(0.3R(L)) + 1.7(m−m_ref))
n → n+1: k_on·Y·(N−n); n → n−1: k_off·n
q = n/N; B(q) = logistic[h·(logit(q)−logit(q_half))]
Y_ref = 3.15 µM; k_on = exchange/(Y_ref + K_D)
k_off = exchange·K_D/(Y_ref + K_D)
CCW → CW: w·B(q); CW → CCW: w·(1−B(q)) [s⁻¹]
mean occupancy: dq̄/dt = k_on·Y(1−q̄) − k_off·q̄
n(t) ~ Binomial(N, q̄(t))
dP_CW/dt = w·(Σ_n B(n/N)·Pr(n,t) − P_CW)
Displayed curve = P_CW(t); joint-stationary initialization
J = Σ_n P(n,CW)·w·(1−B(n/N))
mean CW dwell = P_CW/J; mean CCW dwell = (1−P_CW)/J
Tumble: ≥2/5 motors CW; full bundle: 0/5 CW</pre><p>${tx('占有率しきい値と回転切替速度：現在値・適合根拠は校正パネルに表示します。以下は未校正パラメーターの初期値です。','Occupancy threshold and motor switching scale: current values and fit provenance are shown in the calibration panel. The table lists initial values of uncalibrated parameters.')}</p><table><tr><th>Parameter</th><th>Default</th><th>${tx('根拠','Provenance')}</th></tr>${[['K_D','3.15 µM'],['Binding exchange at Y_ref=3.15 µM','6.3 s⁻¹'],['Derived k_on / k_off','1 µM⁻¹ s⁻¹ / 3.15 s⁻¹'],['N','34'],['h','9.5'],['CheA/Y/Z/R/B','1×'],['Exploratory stimulus K (Asp/Ser/Ni/Co)','2 / 8 / 20 / 35 µM'],['stimulus e','1.15 / 1.15 / 1.05 / 0.95']].map(v=>`<tr><td>${v[0]}</td><td>${v[1]}</td><td>${tx('未校正・モデル仮定','Uncalibrated model assumption')}</td></tr>`).join('')}</table><p>Upstream: rate-limited RK4, steady-state root initialization at the background concentration. Display and motor input bins: 0.2 s; response metrics: 0.01 s. CheA-short is non-phosphorylatable. CheZ is counted as monomers (two sites per dimer). Motor-bound CheY depletion and CheZ complexes are omitted; the phosphorylated pathway pool approximates free motor input. Clamp input does not alter conserved pathway pools. Effective modification is not a literal methyl-group count.</p><p>Protein reference: <a href="https://doi.org/10.1128/JB.186.12.3687-3694.2004">Li &amp; Hazelbauer 2004</a>, RP437/TB/35°C; the 1 fL volume is assumed. kAY=100 µM⁻¹s⁻¹ is the low-substrate approximation of 650 s⁻¹ / 6.5 µM (<a href="https://doi.org/10.1021/bi962261k">Stewart 1997</a>), not a validated whole-cell rate. kYoff=2.2/60 s⁻¹ (<a href="https://doi.org/10.1128/JB.00853-15">2016 study</a>). kZ=4.9 s⁻¹ (<a href="https://pubmed.ncbi.nlm.nih.gov/17998207/">CheZ kinetic study</a>); the Hill-2 law, KZ=3 µM and site normalization are model assumptions. kAuto=20 s⁻¹, kAB=10 µM⁻¹s⁻¹, kBoff=1 s⁻¹, kR=kB=0.08 µM⁻¹s⁻¹ are exploratory defaults. CheB-P activation factor 100 is an approximation (<a href="https://doi.org/10.1021/bi012102n">Anand &amp; Stock 2002</a>). Rates from different assays are not a jointly calibrated in-vivo parameter set. All parameters and reference scope are exported.</p><p>${tx('参考文献（条件付きの対応は校正パネル参照）','References (conditional correspondence documented in the calibration panel)')}: <a href="https://doi.org/10.1126/science.287.5458.1652" target="_blank" rel="noopener">Cluzel et al., 2000</a>; <a href="https://doi.org/10.1073/pnas.192463199" target="_blank" rel="noopener">Sourjik & Berg, 2002</a>.</p>`;}
const dictionary={
'標準条件に戻す':'Reset defaults','確率過程を再試行':'New stochastic trace','実験条件':'Conditions','タンパク質量を野生型比で変更します。':'Protein abundance relative to wild type.','ヒスチジンキナーゼ':'Histidine kinase','応答調節因子':'Response regulator','脱リン酸化促進':'Dephosphorylation','受容体メチル化':'Receptor methylation','受容体脱メチル化':'Receptor demethylation','刺激物質':'Stimulus','誘引物質':'Attractants','忌避物質':'Repellents','添加後濃度':'Final concentration','添加時刻':'Addition time','比較プリセット':'Presets','適応欠損':'Reduced adaptation','走化性シグナル伝達':'Chemotaxis signaling','受容体活性':'Receptor activity','相対活性':'Relative activity','リン酸転移':'Phosphotransfer','FliM結合':'FliM binding','応答ピーク':'Response peak','応答時間':'Response time','適応誤差':'Adaptation error','Tumble時間率':'Tumble fraction','刺激前':'Pre-stimulus','大腸菌内シグナルとモーター反転':'Intracellular signaling & motor switching','極性受容体クラスター':'Polar receptor clusters','低速再生':'Slow playback','細胞内シグナル':'Intracellular signals','べん毛モーター':'Flagellar motors','定常CW biasへの寄与':'Final ensemble CW sensitivity','各因子を単独で+10%変化':'Each factor increased by 10%','CheY-P相対解離速度':'CheY-P dissociation rate','相対結合寿命':'Binding lifetime','モデルについて':'About the model','完全形成':'Full bundle','部分形成':'Partial bundle','解離':'Dispersed','適応応答':'Adapted response','部分適応':'Partial adaptation','高CW固定傾向':'High CW bias','低CW固定傾向':'Low CW bias','べん毛束':'Flagellar bundle','誘引':'Attractant','忌避':'Repellent','刺激':'Stimulus','結合部位数':'Binding sites','切替応答の急峻さ':'Switching steepness','協同性':'Switching steepness','半応答占有率':'Half-response occupancy'};
const originals=new WeakMap();
function translate(){document.documentElement.lang=language;document.querySelectorAll('[data-ja]').forEach(n=>{const value=n.dataset[language];if(n.textContent!==value)n.textContent=value;});const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(n.parentElement.closest('script,style,[data-ja],#modelDocs'))continue;const cached=originals.get(n);let source=cached&&n.nodeValue===cached.result?cached.source:n.nodeValue;let result=source;if(language==='en')for(const [ja,en] of Object.entries(dictionary).sort((a,b)=>b[0].length-a[0].length))result=result.split(ja).join(en);if(n.nodeValue!==result)n.nodeValue=result;originals.set(n,{source,result});}document.querySelectorAll('optgroup').forEach(n=>{if(n.label==='誘引物質'||n.label==='Attractants')n.label=tx('誘引物質','Attractants');if(n.label==='忌避物質'||n.label==='Repellents')n.label=tx('忌避物質','Repellents');});}
el('langBtn').onclick=()=>{language=language==='ja'?'en':'ja';el('langBtn').textContent=language==='ja'?'English':'Japanese';docs();translate();showBatch();renderCellScene(lastResult,Math.floor(playbackIndex),flagellaPhase);if(!el('figurePreview').hidden)el('figurePreview').innerHTML=figureSVG();};
document.querySelector('.model-note')?.remove();
renderSensitivity=function(base){const values=axes.map(([id,name])=>({name,val:(simulate({...state,[id]:(state[id]??defaults[id])*1.1}).cw.at(-1)-base)/.1})),max=Math.max(.01,...values.map(v=>Math.abs(v.val)));el('sensitivityBars').innerHTML=values.map(v=>`<div class="sens"><strong>${v.name}</strong><div class="sens-track"><i style="width:${Math.abs(v.val)/max*100}%"></i></div><output>${v.val.toFixed(2)}</output></div>`).join('');};
// Reapply research settings and seeded trace from the visible seed control.
el('seed').addEventListener('change',()=>{try{stochasticSeed=validSettings().seed;runAndRender();}catch(e){el('researchStatus').textContent=e.message;}});
// Clear dependent analyses immediately, including during replacement jobs.
const originalBatch=runBatch,originalGrid=runGrid;
runBatch=async function(){el('statistics').innerHTML=el('dwellPlot').innerHTML='';el('figurePreview').hidden=true;await originalBatch();};
const baseShowBatch=showBatch;
showBatch=function(){baseShowBatch();if(batch){const complete=batch.runs.flatMap(r=>r.dwells).filter(d=>!d.left_censored&&!d.right_censored);el('statistics').insertAdjacentHTML('beforeend',`<p>${['CW','CCW'].map(s=>{const values=complete.filter(d=>d.state===s).map(d=>d.duration);if(!values.length)return `${s}: n=0`;const a=E.summary(values);return `${s}: ${a.mean.toFixed(3)} ± ${a.sd.toFixed(3)} s (SD), n=${a.n}`;}).join(' / ')} — ${tx('完全滞在区間のみ','complete dwell intervals only')}</p>`);}};
runGrid=async function(){el('heatmap').innerHTML='';el('gridDetail').textContent='';el('figurePreview').hidden=true;await originalGrid();};
el('batchBtn').onclick=guarded(runBatch);el('gridBtn').onclick=guarded(runGrid);
for(const id of ['axisX','axisY','gridMetric','gridSize','gridReps'])el(id).onchange=()=>{job++;grid=null;el('gridCsv').disabled=true;el('heatmap').innerHTML='';el('gridDetail').textContent='';el('figurePreview').hidden=true;};
document.querySelector('.scene-key').insertAdjacentHTML('beforeend','<span data-ja="モーター内の緑弧：CheY-P占有率" data-en="Green motor arc: CheY-P occupancy"></span>');
document.querySelector('.node.motor b').textContent='Ensemble CW probability';
document.querySelector('.motor-kinetics').innerHTML='<span>k_off <strong id="motorKoffReadout"></strong></span><span>1/k_off <strong id="motorLifetimeReadout"></strong></span>';
// Include exact parameter provenance in every exported SVG, including Figure mode.
el('exportTarget').insertAdjacentHTML('beforeend','<option value="sensitivity">Sensitivity</option><option value="trajectory">Trajectory</option>');
function sensitivitySVG(){const base=simulate(state).cw.at(-1),values=axes.map(([id,name])=>({name,value:(simulate({...state,[id]:(state[id]??defaults[id])*1.1}).cw.at(-1)-base)/.1})),max=Math.max(.01,...values.map(v=>Math.abs(v.value)));return svgWrap(textSVG(20,25,'Local ensemble sensitivity: +10% change')+values.map((v,i)=>textSVG(20,55+i*28,v.name)+`<rect x="${350+Math.min(0,v.value)/max*210}" y="${40+i*28}" width="${Math.abs(v.value)/max*210}" height="18" fill="${v.value<0?'#ba4a00':'#007f77'}"/>`+textSVG(600,55+i*28,v.value.toFixed(4))).join('')+'<path d="M350 35V335" stroke="#172b35"/>');}
function trajectorySVG(){let x=360,y=180,angle=-.25,path='M360 180';for(let i=1;i<lastMotorTrace.length;i+=5){if(lastMotorTrace[i].filter(Boolean).length>=2)angle+=1.7*Math.sin(i*12.9898);else{x+=Math.cos(angle)*2.2;y+=Math.sin(angle)*2.2;}if(x<5||x>715){angle=Math.PI-angle;x=Math.max(5,Math.min(715,x));}if(y<5||y>355){angle=-angle;y=Math.max(5,Math.min(355,y));}path+=`L${x},${y}`;}return svgWrap(textSVG(20,25,'Illustrative trajectory (arbitrary units; not physical run length)')+`<path d="${path}" fill="none" stroke="#007f77" stroke-width="2"/>`);}
const oldSelectedSVG=selectedSVG;
const plainSelectedSVG=()=>el('exportTarget').value==='sensitivity'?sensitivitySVG():el('exportTarget').value==='trajectory'?trajectorySVG():oldSelectedSVG();
selectedSVG=function(){const s=plainSelectedSVG(),end=s.indexOf('>');return s.slice(0,end+1)+`<metadata>${esc(JSON.stringify({model:'0.6',params:state,upstream:lastResult.audit,response_metrics:lastResult.metrics,traceSeed:lastMotorTrace.seed,calibration_current:typeof calibrationMatches==='function'?calibrationMatches(state):false,derived_rates:E.config(state),batch:batch?{seed:batch.seed,n:batch.runs.length,start:batch.start}:null,sweep:grid?{seed:grid.seed,n:grid.n,start:grid.start,x:grid.x,y:grid.y,metric:grid.metric}:null}))}</metadata>`+s.slice(end+1);};
Object.assign(dictionary,{
  '条件変更後は再計算してください。':'Recompute analyses after changing conditions.',
  '反復計算完了':'Batch complete','探索完了':'Sweep complete','計算を中止しました。':'Calculation cancelled.',
  '反復計算が必要です':'Run a batch first','探索計算が必要です':'Run a sweep first','完全滞在区間のみ':'complete dwell intervals only',
  'Seedまたは解析開始時刻が不正です。':'Invalid seed or analysis start.','異なる軸を選んでください。':'Choose different axes.',
  '同一条件で新しい確率的切替系列を生成':'Generate a new stochastic trace under the same conditions',
  '受容体からべん毛モーターまでのシグナル経路':'Signaling pathway from receptor to flagellar motor',
  '大腸菌内のCheY-P濃度とべん毛モーター回転を表すCGアニメーション':'CG animation of intracellular CheY-P and motor rotation',
  'アニメーションを一時停止':'Pause animation','アニメーションを再生':'Play animation',
  'シミュレーション時刻':'Simulation time','CheY-PとCW biasの時系列グラフ':'Time courses of CheY-P and CW probability',
  '細胞運動軌跡':'Cell trajectory','形成':'Bundled'
});
const attributeSources=new WeakMap(),translateText=source=>Object.entries(dictionary).sort((a,b)=>b[0].length-a[0].length).reduce((s,[ja,en])=>s.split(ja).join(en),source);
const translateBody=translate;
translate=function(){translateBody();document.title=tx('ChemoSim — 大腸菌走化性シミュレーター','ChemoSim — E. coli chemotaxis simulator');document.querySelectorAll('[title],[aria-label]').forEach(node=>{let cache=attributeSources.get(node)||{};for(const attr of ['title','aria-label']){if(!node.hasAttribute(attr))continue;const value=node.getAttribute(attr),old=cache[attr],source=old&&value===old.result?old.source:value,result=language==='en'?translateText(source):source;node.setAttribute(attr,result);cache[attr]={source,result};}attributeSources.set(node,cache);});};
for(const [id] of knobs){const input=el('r_'+id),handler=input.onchange;input.onchange=()=>{if(id==='sites')input.value=Math.round(Number(input.value));handler();};}
// Clear stale figure and cell details when analysis settings change.
for(const id of ['seed','windowStart','replicates']){const handler=el(id).onchange;el(id).onchange=()=>{handler();el('figurePreview').hidden=true;el('gridDetail').textContent='';};}
const researchRun=runAndRender;
runAndRender=function(){el('seed').value=stochasticSeed;researchRun();};
const virtualPresets=[
  {id:'wt',label:'WT',changes:{},ja:'標準条件。上流・結合定数は仮定値です。モーターの校正状態は校正パネル参照。',en:'Reference condition. Upstream and binding parameters are assumptions; see motor calibration status.'},
  {id:'cheZlow',label:'CheZ↓',changes:{cheZ:.25},ja:'CheZ = 0.25倍。部分低下モデル。',en:'CheZ = 0.25×; partial reduction.'},
  {id:'cheZdel',label:'ΔcheZ',changes:{cheZ:0},ja:'CheZ = 0。CheZ依存の脱リン酸化のみ除去し、基礎脱リン酸化は残します。',en:'CheZ = 0. Removes CheZ-dependent dephosphorylation; basal removal remains.'},
  {id:'cheYhigh',label:'CheY↑',changes:{cheY:3},ja:'CheY = 3倍。過剰発現の仮想条件。',en:'CheY = 3×; illustrative overexpression.'},
  {id:'fliMweak',label:'FliM binding↓',changes:{kd:12.6,exchange:3.9375},ja:'k_on = 0.25 µM⁻¹ s⁻¹。結合能低下の仮説。特定のFliM変異の実測値ではありません。',en:'k_on = 0.25 µM⁻¹ s⁻¹. Reduced-binding hypothesis, not a measured FliM allele.'},
  {id:'fastOff',label:'Fast dissociation',changes:{kd:6.3,exchange:9.45},ja:'k_off = 6.3 s⁻¹。解離促進の仮説条件。',en:'k_off = 6.3 s⁻¹; accelerated dissociation hypothesis.'},
  {id:'adaptOff',label:'ΔcheR ΔcheB',changes:{cheR:0,cheB:0},ja:'CheR = CheB = 0。モデル内のメチル化適応を停止します。',en:'CheR = CheB = 0; methylation adaptation is disabled in this model.'},
  {id:'highSensitivity',label:'High sensitivity',changes:{threshold:.4},ja:'半応答占有率 = 0.40。少ない結合でCW応答が生じる仮説。',en:'Half-response occupancy = 0.40; CW response at lower occupancy.'},
  {id:'lowSensitivity',label:'Low sensitivity',changes:{threshold:.6},ja:'半応答占有率 = 0.60。CW応答により多くの結合を要する仮説。',en:'Half-response occupancy = 0.60; more occupancy required for CW response.'},
  {id:'ecoliReference',label:'E. coli reference*',changes:{},ja:'菌種比較用の基準。大腸菌の実測値への適合ではありません。',en:'Illustrative species-comparison reference; not fitted to E. coli measurements.'},
  {id:'salmonellaHypothesis',label:'Salmonella hypothesis*',changes:{exchange:3.15},ja:'結合・解離をともに0.5倍とする仮説。親和性比は維持。サルモネラの実測値や切替頻度の低下を保証する条件ではありません。',en:'Hypothesis: both binding and dissociation are halved, keeping their ratio fixed. Not measured Salmonella parameters or a guarantee of lower switching frequency.'}
];
document.querySelector('.preset-grid').innerHTML=virtualPresets.map(p=>`<button type="button" id="preset_${p.id}" class="preset" data-preset="${p.id}">${p.label}</button>`).join('');
document.querySelector('.preset-section').insertAdjacentHTML('beforeend','<p id="presetNote" class="helper" aria-live="polite"></p><p class="helper" data-ja="プリセットは刺激条件を保持します。スライダー左端は0（欠損）、次の位置は0.25倍。CheZアイコンは相対量の模式表示（1倍＝4個）です。*菌種比較は未検証の仮説です。" data-en="Presets retain the stimulus settings. The left slider endpoint is 0 (deletion), followed by 0.25×. CheZ icons show relative abundance (1× = 4 icons), not molecule counts. *Species comparisons are unvalidated hypotheses."></p>');
for(const p of virtualPresets)el('preset_'+p.id).onclick=()=>applyState({...defaults,ligand:state.ligand,stepTime:state.stepTime,ligandType:state.ligandType,background:state.background,volumeFL:state.volumeFL,receptorProfile:state.receptorProfile,freezeModification:state.freezeModification,modification:state.modification,...p.changes,presetId:p.id},p.id);
defaults.presetId='wt';state.presetId='wt';
const priorClearPreset=clearPreset;clearPreset=function(){state.presetId=null;priorClearPreset();};
const presetRun=runAndRender;
runAndRender=function(){const p=virtualPresets.find(p=>p.id===state.presetId);el('presetNote').dataset.ja=p?p.ja:'カスタム条件';el('presetNote').dataset.en=p?p.en:'Custom condition';presetRun();};
docs();runAndRender();
