/* Concentrations µM, time s, volume fL. ATP is an external reservoir. */
const Upstream=(()=>{
const defaults={volumeFL:1,background:0,receptorProfile:'explore',freezeModification:false,modification:2,kAuto:20,kAY:100,kAB:10,kYoff:2.2/60,kBoff:1,kZ:4.9,KZ:3,kR:.08,kB:.08};
const counts={AL:4500,AS:2200,Y:8200,Z:3200,R:140,B:240};
const profiles={tarEEEE:{ligand:'measp',name:'Tar EEEE / ΔcheRcheB / MeAsp',beta:.65,K:38,K2:83000,h:1.2,source:'10.1073/pnas.011589998',condition:'Zero background; fixed Tar EEEE; mixed receptor cells; normalized CheY/CheZ FRET response'},tarQEQE:{ligand:'measp',name:'Tar QEQE / ΔcheRcheB / MeAsp',beta:.36,K:150,K2:105000,h:1.2,source:'10.1073/pnas.011589998',condition:'Zero background; fixed Tar QEQE; mixed receptor cells; normalized CheY/CheZ FRET response'},tsr:{ligand:'ser',name:'Tsr / WM4196 minicells / serine',beta:1,K:.4,h:2.7,source:'10.1038/s41467-020-14350-9',condition:'Zero background; endogenous adapted modification (not a specified E/Q sequence); initial normalized kinase response; WM4196 minicells'}};
const config=p=>({...defaults,...p});
function totals(p){const c=config(p),v=602.214076*c.volumeFL;return {AL:counts.AL*(c.cheA??1)/v,AS:counts.AS*(c.cheA??1)/v,Y:counts.Y*(c.cheY??1)/v,Z:counts.Z*(c.cheZ??1)/v,R:counts.R*(c.cheR??1)/v,B:counts.B*(c.cheB??1)/v};}
function ratio(L,f){return f.beta/(1+(L/f.K)**f.h)+(1-f.beta)/(1+(L/(f.K2||f.K))**f.h);}
function activity(L,m,p){const f=profiles[p.receptorProfile];let ref;if(f&&f.ligand===p.ligandType)ref=.3*ratio(L,f);else{const d={asp:[2,1.15,1],measp:[2.6,1.2,1],ser:[8,1.15,1],ni:[20,1.05,-1],co:[35,.95,-1]}[p.ligandType]||[2,1.15,1];ref=1/(1+Math.exp(Math.log(7/3)+d[2]*d[1]*Math.log1p(L/d[0])));}ref=Math.max(1e-14,Math.min(1-1e-14,ref));return 1/(1+Math.exp(-Math.log(ref/(1-ref))-1.7*(m-p.modification)));}
function derivative(x,L,p,T){const [ap,yp,bp,m]=x,a=activity(L,m,p),va=p.kAuto*a*(T.AL-ap),vy=p.kAY*ap*(T.Y-yp),vb=p.kAB*ap*(T.B-bp),vz=p.kYoff*yp+p.kZ*T.Z*yp*yp/(p.KZ*p.KZ+yp*yp);let dm=p.freezeModification?0:p.kR*T.R*(1-a)-p.kB*((T.B-bp)+100*bp)*a;if(m<=0&&dm<0||m>=4&&dm>0)dm=0;return [va-vy-vb,vy-vz,vb-p.kBoff*bp,dm];}
function bisect(fn,lo,hi){for(let i=0;i<65;i++){const mid=(lo+hi)/2;if(fn(mid)>0)hi=mid;else lo=mid;}return (lo+hi)/2;}
function steady(p,T){function at(m){const a=activity(p.background,m,p);function pools(ap){const yp=bisect(y=>p.kYoff*y+p.kZ*T.Z*y*y/(p.KZ*p.KZ+y*y)-p.kAY*ap*(T.Y-y),0,T.Y);const bp=T.B*p.kAB*ap/(p.kAB*ap+p.kBoff);return [ap,yp,bp,m];}const ap=bisect(ap=>{const x=pools(ap);return p.kAY*ap*(T.Y-x[1])+p.kAB*ap*(T.B-x[2])-p.kAuto*a*(T.AL-ap);},0,T.AL);return pools(ap);}if(p.freezeModification||T.R===0&&T.B===0)return at(p.modification);const low=at(0),high=at(4);if(derivative(low,p.background,p,T)[3]===0)return low;if(derivative(high,p.background,p,T)[3]===0)return high;return at(bisect(m=>-derivative(at(m),p.background,p,T)[3],0,4));}
function metrics(t,y,step,baseline){const begin=t.findIndex(v=>v>=step-1e-8);let peak=begin;for(let i=begin;i<t.length;i++)if(Math.abs(y[i]-baseline)>Math.abs(y[peak]-baseline))peak=i;const delta=y[peak]-baseline,amp=Math.abs(delta);if(amp<1e-8)return {baseline,delta:0,excitation90:null,recovery50:null,precision:null,residualPercent:null,status:'no response'};const cross=(start,end,target)=>{for(let i=start+1;i<=end;i++){const a=y[i-1]-target,b=y[i]-target;if(a*b<=0&&a!==b)return t[i-1]+(t[i]-t[i-1])*(-a)/(b-a)-step;}return null;};return {baseline,delta,peakTime:t[peak]-step,excitation90:cross(begin,peak,baseline+.9*delta),recovery50:cross(peak,t.length-1,baseline+.5*delta),precision:100*(1-Math.abs(y.at(-1)-baseline)/amp),residualPercent:baseline>1e-9?100*Math.abs(y.at(-1)-baseline)/baseline:null,status:'finite-window',window:60-step};}
function provenance(p){p=config(p);const f=profiles[p.receptorProfile];return {totals_uM:totals(p),volume_fL:p.volumeFL,counts_reference:counts,protein_source:'10.1128/JB.186.12.3687-3694.2004; RP437, TB, 35°C; volume is an independent assumption',receptor:f||null,reference_curve_current:!!f&&p.ligandType===f.ligand&&p.background===0&&p.freezeModification,scope:'Published normalized response curve reconstruction, not independent validation of absolute kinase activity or downstream dynamics',rates:Object.fromEntries(Object.keys(defaults).filter(k=>k.startsWith('k')||k==='KZ').map(k=>[k,p[k]]))};}
const cache=new Map();
function simulate(input){const p=config(input),keys=[...Object.keys(defaults),'cheA','cheY','cheZ','cheR','cheB','ligand','ligandType','stepTime','solverScale'],key=JSON.stringify(keys.map(k=>p[k]));if(cache.has(key))return structuredCopy(cache.get(key));const T=totals(p);let x=steady(p,T);const initial=x.slice(),r={time:[],activity:[],cheAP:[],cheYP:[],cheBP:[],cheAFree:[],cheYFree:[],cheBFree:[],methylation:[],cw:[],stimulus:[]},fineT=[],fineY=[];
const hmax=(p.solverScale||1)*Math.min(.005,.8/(p.kAY*(T.Y+T.AL)+p.kAB*(T.B+T.AL)+p.kAuto+p.kZ*T.Z/p.KZ+p.kBoff+p.kYoff+1.7*(p.kR*T.R+100*p.kB*T.B)+1));let t=0;
function advance(end,L){while(t<end-1e-12){const h=Math.min(hmax,end-t),a=derivative(x,L,p,T),b=derivative(x.map((v,j)=>v+h*a[j]/2),L,p,T),c=derivative(x.map((v,j)=>v+h*b[j]/2),L,p,T),d=derivative(x.map((v,j)=>v+h*c[j]),L,p,T);x=x.map((v,j)=>v+h*(a[j]+2*b[j]+2*c[j]+d[j])/6);x[3]=Math.max(0,Math.min(4,x[3]));t+=h;}}
for(let i=0;i<=6000;i++){const target=i/100;if(t<p.stepTime&&target>p.stepTime)advance(p.stepTime,p.background);advance(target,t<p.stepTime-1e-10?p.background:p.ligand);fineT.push(target);fineY.push(x[1]);if(i%20===0){r.time.push(target);r.activity.push(activity(target<p.stepTime?p.background:p.ligand,x[3],p));r.cheAP.push(x[0]);r.cheYP.push(x[1]);r.cheBP.push(x[2]);r.cheAFree.push(T.AL-x[0]);r.cheYFree.push(T.Y-x[1]);r.cheBFree.push(T.B-x[2]);r.methylation.push(x[3]);r.cw.push(0);r.stimulus.push(target<p.stepTime?p.background:p.ligand);}}
r.cheYPpool=r.cheYP.slice();r.metrics=metrics(fineT,fineY,p.stepTime,initial[1]);r.audit={...provenance(p),steadyResidual:Math.max(...derivative(initial,p.background,p,T).map(Math.abs)),initial,baselineDrift:Math.max(0,...fineY.filter((_,i)=>fineT[i]<p.stepTime).map(v=>Math.abs(v-initial[1]))),solver:'RK4, rate-limited step; metrics sampled at 0.01 s',hmax};if(cache.size>120)cache.clear();cache.set(key,r);return structuredCopy(r);}
function structuredCopy(r){return JSON.parse(JSON.stringify(r));}
return {defaults,profiles,counts,config,totals,ratio,activity,derivative,steady,simulate,metrics,provenance};
})();
if(typeof module!=='undefined')module.exports=Upstream;
