/* Upstream controls and auditable exports. */
el('ligandSelect').insertAdjacentHTML('beforeend','<option value="measp">MeAsp (Tar)</option>');
document.querySelector('.results-panel').insertAdjacentHTML('afterbegin',`<section class="research-card"><h2 data-ja="上流反応・参照条件" data-en="Upstream reactions & reference conditions"></h2><div class="research-toolbar"><label><span data-ja="細胞体積 (fL)" data-en="Cell volume (fL)"></span><input id="u_volumeFL" type="number" min="0.25" max="5" step="0.05"></label><label><span data-ja="背景濃度 (µM)" data-en="Background (µM)"></span><input id="u_background" type="number" min="0" max="100000" step="0.1"></label><label><span data-ja="修飾の基準座標 (0–4)" data-en="Reference modification coordinate (0–4)"></span><input id="u_modification" type="number" min="0" max="4" step="0.1"></label><label><input id="u_freezeModification" type="checkbox"><span data-ja="修飾を固定（初期応答の参照用）" data-en="Freeze modification (initial-response reference)"></span></label><select id="u_profile"><option value="explore">Exploratory / uncalibrated</option>${Object.entries(Upstream.profiles).map(([id,f])=>`<option value="${id}">${f.name}</option>`).join('')}</select><button id="upstreamCsv" data-ja="反応量・指標CSV" data-en="Pools & metrics CSV"></button><button id="doseCsv" data-ja="参照濃度応答CSV" data-en="Reference dose-response CSV"></button></div><p id="upstreamScope"></p><div id="doseTable"></div><div id="poolTable"></div><p id="baselineAudit"></p><div class="metrics-grid"><article class="metric"><span data-ja="興奮時間 t90" data-en="Excitation t90"></span><strong id="u_excitation"></strong><small data-ja="刺激からピーク変化量の90%まで" data-en="From stimulus to 90% of peak change"></small></article><article class="metric"><span data-ja="適応50%回復時間" data-en="Adaptation 50% recovery"></span><strong id="u_recovery"></strong><small data-ja="刺激から、ピーク後の半回復まで" data-en="From stimulus to half recovery after peak"></small></article><article class="metric"><span data-ja="観測窓内の適応精度" data-en="Finite-window adaptation precision"></span><strong id="u_precision"></strong><small>100 × (1 − |Y_end − Y_base| / |Y_peak − Y_base|)</small></article></div><p class="helper" data-ja="指標は経路内CheY-Pに基づきます。モーター入力固定時も経路の反応量を別に記録します。未回復は観測窓超過と表示。濃度応答の文献対応は初期の正規化応答のみで、絶対濃度・適応時間の校正ではありません。" data-en="Metrics use pathway CheY-P. Motor clamp input is recorded separately from the pathway pool. Unrecovered responses are marked beyond the observation window. Literature correspondence covers initial normalized response only, not absolute concentrations or adaptation times."></p><details><summary data-ja="反応速度の仮定値を編集" data-en="Edit reaction-rate assumptions"></summary><div class="research-toolbar">${['kAuto','kAY','kAB','kYoff','kBoff','kZ','KZ','kR','kB'].map(id=>`<label>${id} (${['kAY','kAB','kR','kB'].includes(id)?'µM⁻¹ s⁻¹':id==='KZ'?'µM':'s⁻¹'})<input id="u_${id}" type="number" min="0.0001" max="1000" step="0.01"></label>`).join('')}</div></details></section>`);
const uKeys=['volumeFL','background','modification','kAuto','kAY','kAB','kYoff','kBoff','kZ','KZ','kR','kB'];
for(const id of uKeys)el('u_'+id).onchange=()=>{const e=el('u_'+id),v=Number(e.value);const min=Number(e.min||({volumeFL:.25,background:0,modification:0}[id]??.0001)),max=Number(e.max||({volumeFL:5,background:100000,modification:4}[id]??1000));if(e.value.trim()===''||!Number.isFinite(v)||v<min||v>max){e.value=state[id];return;}state[id]=v;runAndRender();};
el('u_freezeModification').onchange=()=>{state.freezeModification=el('u_freezeModification').checked;runAndRender();};
el('u_profile').onchange=()=>{state.receptorProfile=el('u_profile').value;const f=Upstream.profiles[state.receptorProfile];if(f){state.ligandType=f.ligand;state.background=0;state.freezeModification=true;state.modification=2;if(state.receptorProfile.startsWith('tar')){state.cheR=0;state.cheB=0;}else{state.cheR=1;state.cheB=1;}applyState(state,null);}else runAndRender();};
function renderUpstream(){const r=lastResult,p=Upstream.config(state),a=r.audit,m=r.metrics;for(const id of uKeys)el('u_'+id).value=p[id];el('u_freezeModification').checked=p.freezeModification;el('u_profile').value=p.receptorProfile;el('poolTable').innerHTML=`<table><tr><th>Pool</th><th>${tx('総濃度 (µM)','Total (µM)')}</th><th>${tx('分子数 / 細胞','Molecules / cell')}</th></tr>${Object.entries(a.totals_uM).map(([id,v])=>`<tr><td>Che${id==='AL'?'A-long':id==='AS'?'A-short':id}</td><td>${v.toFixed(4)}</td><td>${(v*602.214076*p.volumeFL).toFixed(0)}</td></tr>`).join('')}</table>`;
const f=Upstream.profiles[p.receptorProfile];el('doseTable').innerHTML=f?`<table><tr><th>Ligand (µM)</th><th>Published R(L)</th><th>Reference a(L)/a(0)</th></tr>${[0,f.K,f.K*10,f.K2||f.K*100].map(L=>`<tr><td>${L}</td><td>${Upstream.ratio(L,f).toFixed(5)}</td><td>${(Upstream.activity(L,p.modification,{...p,ligandType:f.ligand})/Upstream.activity(0,p.modification,{...p,ligandType:f.ligand})).toFixed(5)}</td></tr>`).join('')}</table>`:'';
el('upstreamScope').textContent=a.receptor?`${a.reference_curve_current?tx('参照曲線再構成','Reference curve reconstruction'):tx('条件変更：未校正の外挿','Changed conditions: uncalibrated extrapolation')} — ${a.receptor.condition}; DOI ${a.receptor.source}`:tx('探索モデル：この物質・修飾状態の濃度応答は未校正です。','Exploratory model: concentration response is uncalibrated for this ligand/modification condition.');el('baselineAudit').textContent=tx('刺激前の最大変動','Maximum pre-stimulus drift')+`: ${a.baselineDrift.toExponential(2)} µM; `+tx('初期定常残差','Initial steady-state residual')+`: ${a.steadyResidual.toExponential(2)} (µM/s or coordinate/s)`;const time=v=>v===null?'—':v.toFixed(2)+' s';el('u_excitation').textContent=time(m.excitation90);el('u_recovery').textContent=m.recovery50===null?(m.delta?`> ${m.window.toFixed(1)} s`:'—'):time(m.recovery50);el('u_precision').textContent=m.precision===null?'—':m.precision.toFixed(1)+'%';el('responseMetric').textContent=time(m.excitation90);el('adaptMetric').textContent=m.residualPercent===null?'—':m.residualPercent.toFixed(1)+'%';el('peakMetric').textContent=m.delta?`${m.delta.toFixed(2)} µM`:'—';document.querySelector('.node.kinase b').textContent='CheA-long-P (µM)';translate();}
const previousUpstreamRun=runAndRender;runAndRender=function(){previousUpstreamRun();renderUpstream();};
const previousUpstreamLang=el('langBtn').onclick;el('langBtn').onclick=()=>{previousUpstreamLang();renderUpstream();};
el('upstreamCsv').onclick=()=>{const r=lastResult,meta=JSON.stringify({model:'0.6',params:state,audit:r.audit,metrics:r.metrics});csv([['metadata','time_s','AL_free_uM','AL_P_uM','Y_free_uM','Y_P_pool_uM','B_free_uM','B_P_uM','modification_coordinate','motor_input_Y_P_uM'],...r.time.map((t,i)=>[meta,t,r.cheAFree[i],r.cheAP[i],r.cheYFree[i],r.cheYPpool[i],r.cheBFree[i],r.cheBP[i],r.methylation[i],r.cheYP[i]])],'chemosim-upstream.csv');};
el('doseCsv').onclick=()=>{const p=Upstream.config(state),f=Upstream.profiles[p.receptorProfile];if(!f){el('upstreamScope').textContent=tx('参照プロファイルを選択してください。','Select a reference profile first.');return;}csv([['metadata','ligand_uM','published_normalized_response','implemented_reference_response'],...Array.from({length:101},(_,i)=>{const L=i?10**(-3+(i-1)*.09):0;return [JSON.stringify(Upstream.provenance(p)),L,Upstream.ratio(L,f),Upstream.activity(L,p.modification,{...p,ligandType:f.ligand})/Upstream.activity(0,p.modification,{...p,ligandType:f.ligand})];})],'chemosim-reference-dose.csv');};
renderUpstream();
